### ISSUE TITLE
feat: Implementing `eth_estimateGas` method

### ISSUE THREAD

**Issue by Boreas09** [Digine-Labs/rosettanet#111]
## Description

https://github.com/keep-starknet-strange/rosettanet/blob/main/rpc-call-examples/eth_estimateGas.hurl
https://github.com/keep-starknet-strange/rosettanet/blob/main/rpc-call-examples/starknet_estimateFee.hurl

## Requirements

Unit tests have to be implemented.
Do not change the existing type structure
Tests must have non-existent transaction results as well.

## Completion Time

The issue is assumed to be completed in 5 days.

**Comment by Boreas09** [comment]
I want to self assign this issue

**Comment by ermvrs** [comment]
assigned

**Comment by ermvrs** [comment]
Please complete as soon as possible 🙏

**Comment by ermvrs** [comment]
https://github.com/Digine-Labs/rosettanet/pull/125
