### ISSUE TITLE
Error Codes

### ISSUE THREAD

**Issue by Boreas09** [Digine-Labs/rosettanet#130]
Returning infura type errors described [here](https://docs.infura.io/api/networks/ethereum/json-rpc-methods#json-rpc-errors) : https://docs.infura.io/api/networks/ethereum/json-rpc-methods#json-rpc-errors

**Comment by ermvrs** [comment]
https://github.com/Digine-Labs/rosettanet/pull/131

For unimplemented methods

**Comment by ermvrs** [comment]
@Boreas09 can you confirm which http status code returns on method failures

**Comment by Boreas09** [comment]
Infura returns 200 ok in method failures.
<img width="634" alt="Screenshot_1" src="https://github.com/Digine-Labs/rosettanet/assets/90131638/374c26ec-6645-4622-8fed-b26b4a8a1c55">
