### ISSUE TITLE
feat: Implement eth_getUncleByBlockNumberAndIndex

### ISSUE THREAD

**Issue by Boreas09** [Digine-Labs/rosettanet#184]
Returns the compiled byte code of a smart contract, if any, at a given address.

**Parameters :**

* `blockParameter`: Hexadecimal or decimal integer representing a block number, or one of the string tags:`latest`,`earliest`,`pending`,`finalized`,`safe`
* `uncle index position`: [Required] A hexadecimal equivalent of the integer indicating the uncle's index position.

**Returns :** 

A block object, or null when no block was found. The block object returned will consist of the following keys and their values:

* `number`: The block number. Null when the returned block is the pending block.
* `hash`: 32 bytes. Hash of the block. Null when its pending block.
* `parentHash`: 32 bytes. Hash of the parent block.
* `nonce`: 8 bytes. Hash of the generated proof-of-work. Null when the returned block is the pending block.
* `sha3Uncles`: 32 bytes. The SHA3 of the uncles data in the block.
* `logsBloom`: 256 bytes. The Bloom filter for the logs of the block. Null when the returned block is the pending block.
* `transactionsRoot`: 32 bytes. The root of the transaction trie of the block.
* `stateRoot`: 32 bytes. The root of the final state trie of the block.
* `receiptsRoot`: 32 bytes. The root of the receipts trie of the block.
* `miner`: 20 bytes. The address of the beneficiary to whom the mining rewards were given.
* `difficulty`: The hexadecimal of the difficulty for this block.
* `totalDifficulty`: The hexadecimal of the total difficulty of the chain until this block.
* `extraData`: The "extra data" field of this block.
* `size`: The hexadecimal of the size of this block in bytes.
* `gasLimit`: Maximum gas allowed in this block.
* `gasUsed`: Total used gas by all transactions in this block.
* `timestamp`: The unix timestamp for when the block was collated.
* `uncles`: (Array). An array of uncle hashes.

**Request :**

```[json]
curl https://mainnet.infura.io/v3/YOUR-API-KEY \
  -X POST \
  -H "Content-Type: application/json" \
  -d '{"jsonrpc":"2.0","method":"eth_getUncleByBlockHashAndIndex","params": ["0xb3b20624f8f0f86eb50dd04688409e5cea4bd02d700bf6e79e9384d47d6a5a35","0x0"],"id":1}'
```

**Response :**

```[json]
{
   "id" : 1,
   "jsonrpc" : "2.0",
   "result" : {
     "difficulty": "0x57f117f5c",
     "extraData": "0x476574682f76312e302e302f77696e646f77732f676f312e342e32",
     "gasLimit": "0x1388",
     "gasUsed": "0x0",
     "hash": "0x932bdf904546a2287a2c9b2ede37925f698a7657484b172d4e5184f80bdd464d",
     "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
     "miner": "0x5bf5e9cf9b456d6591073513de7fd69a9bef04bc",
     "mixHash": "0x4500aa4ee2b3044a155252e35273770edeb2ab6f8cb19ca8e732771484462169",
     "nonce": "0x24732773618192ac",
     "number": "0x299",
     "parentHash": "0xa779859b1ee558258b7008bbabff272280136c5dd3eb3ea3bfa8f6ae03bf91e5",
     "receiptsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
     "sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
     "size": "0x21d",
     "stateRoot": "0x2604fbf5183f5360da249b51f1b9f1e0f315d2ff3ffa1a4143ff221ad9ca1fec",
     "timestamp": "0x55ba4827",
     "totalDifficulty": null,
     "transactionsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
     "uncles": []
   }
}
```

## DO NOT FORGET TO UPDATE [methodsStatus.md](https://github.com/Digine-Labs/rosettanet/blob/main/docs/methodsStatus.md) (set this method as finished)

/rosettanet/docs/methodsStatus.md

[methodsStatus.md](https://github.com/Digine-Labs/rosettanet/blob/main/docs/methodsStatus.md)

**Comment by kateberryd** [comment]
Hi
