### ISSUE TITLE
feat: Implement eth_getUncleCountByBlockHash

### ISSUE THREAD

**Issue by Boreas09** [Digine-Labs/rosettanet#185]
Returns the number of uncles in a block from a block matching the given block hash.

**Parameters :**

* `block hash`: [Required] A string representing the hash (32 bytes) of a block.

**Returns :** 

* `block uncle count`: A hexadecimal equivalent of the integer representing the number of uncles in the block.

**Request :**

```[json]
curl https://mainnet.infura.io/v3/YOUR-API-KEY \
  -X POST \
  -H "Content-Type: application/json" \
  -d '{"jsonrpc":"2.0","method":"eth_getUncleCountByBlockHash","params": ["0xb3b20624f8f0f86eb50dd04688409e5cea4bd02d700bf6e79e9384d47d6a5a35"],"id":1}'
```

**Response :**

```[json]
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": "0x1"
}
```

## DO NOT FORGET TO UPDATE [methodsStatus.md](https://github.com/Digine-Labs/rosettanet/blob/main/docs/methodsStatus.md) (set this method as finished)

/rosettanet/docs/methodsStatus.md

[methodsStatus.md](https://github.com/Digine-Labs/rosettanet/blob/main/docs/methodsStatus.md)

**Comment by Jemiiah** [comment]
I would love to work on this

**Comment by ooochoche** [comment]
@Boreas09 I can handle this

**Comment by EjembiEmmanuel** [comment]
@Boreas09 I'd love to work on this
