### ISSUE TITLE
feat: Implement eth_getUncleCountByBlockNumber

### ISSUE THREAD

**Issue by Boreas09** [Digine-Labs/rosettanet#186]
Returns the number of uncles in a block from a block matching the given block number.

**Parameters :**

* `blockParameter`: Hexadecimal or decimal integer representing a block number, or one of the string tags:`latest`,`earliest`,`pending`,`finalized`,`safe`

**Returns :** 

* `block uncle count`: A hexadecimal equivalent of the integer representing the number of uncles in the block.

**Request :**

```[json]
curl https://mainnet.infura.io/v3/YOUR-API-KEY \
  -X POST \
  -H "Content-Type: application/json" \
  -d '{"jsonrpc":"2.0","method":"eth_getUncleCountByBlockNumber","params": ["0x5bad55"],"id":1}'
```

**Response :**

```[json]
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": "0x1"
}
```

## DO NOT FORGET TO UPDATE [methodsStatus.md](https://github.com/Digine-Labs/rosettanet/blob/main/docs/methodsStatus.md) (set this method as finished)

/rosettanet/docs/methodsStatus.md

[methodsStatus.md](https://github.com/Digine-Labs/rosettanet/blob/main/docs/methodsStatus.md)

**Comment by EjembiEmmanuel** [comment]
@Boreas09 I'd love to work on this
