### ISSUE TITLE
feat: Implement eth_getFilterChanges

### ISSUE THREAD

**Issue by Boreas09** [Digine-Labs/rosettanet#191]
Polling method for a filter, which returns an array of logs which occurred since last poll. Filter must be created by calling either eth_newFilter or eth_newBlockFilter.

**Parameters :**

* `filter ID`: A string denoting the filter ID.
**Returns :** 

* log object array: (array) An array of log objects, or an empty array if nothing has changed since last poll.
* For filters created with eth_newBlockFilter the return values are block hashes (32 bytes), e.g. ["0x3454645634534..."].
* For filters created with eth_newFilter the logs are objects with the following params:
* * `address`: 20 bytes. Address from which this log originated.
* * `blockHash`: 32 bytes. The hash of the block where this log was in. Null when it is a pending log.
* * `blockNumber`: The block number where this log was in. Null when it is a pending log.
* * `data`: DATA. Contains the non-indexed arguments of the log.
* * `logIndex`: A hexadecimal of the log index position in the block. Null when it is a pending log.
* * `removed`: true when the log was removed, due to a chain reorganization. false if it is a valid log.
* * `topics`: Array of DATA. An array of 0 to 4 32-bytes DATA of indexed log arguments. In Solidity the first topic is the hash of the signature of the event (e.g. Deposit(address,bytes32,uint256)), except when you declared the event with the anonymous specifier.
* * `transactionHash`: 32 bytes. A hash of the transactions from which this log was created. Null when it is a pending log.
* * `transactionIndex`: A hexadecimal of the transactions index position from which this log was created. Null when it is a pending log.

**Request :**

```[json]
curl https://mainnet.infura.io/v3/YOUR-API-KEY \
    -X POST \
    -H "Content-Type: application/json" \
    -d '{"jsonrpc":"2.0","method":"eth_getFilterChanges","params":["0x10ff0bfbedb01f0dbd4106d14eb719ec38b6eb5b821c"],"id":1}'
```

**Response :**

```[json]
{
    "jsonrpc": "2.0",
    "id": 73,
    "result": [{
        "address": "0xb5a5f22694352c15b00323844ad545abb2b11028",
        "blockHash": "0x99e8663c7b6d8bba3c7627a17d774238eae3e793dee30008debb2699666657de",
        "blockNumber": "0x5d12ab",
        "data": "0x0000000000000000000000000000000000000000000000a247d7a2955b61d000",
        "logIndex": "0x0",
        "removed": false,
        "topics": ["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef", "0x000000000000000000000000bdc0afe57b8e9468aa95396da2ab2063e595f37e", "0x0000000000000000000000007503e090dc2b64a88f034fb45e247cbd82b8741e"],
        "transactionHash": "0xa74c2432c9cf7dbb875a385a2411fd8f13ca9ec12216864b1a1ead3c99de99cd",
        "transactionIndex": "0x3"
    },
    ],
}
```

## DO NOT FORGET TO UPDATE [methodsStatus.md](https://github.com/Digine-Labs/rosettanet/blob/main/docs/methodsStatus.md) (set this method as finished)

/rosettanet/docs/methodsStatus.md

[methodsStatus.md](https://github.com/Digine-Labs/rosettanet/blob/main/docs/methodsStatus.md)

**Comment by Gift-Naomi** [comment]
@Boreas09 can I work on this?
