### ISSUE TITLE
feat: Implement `eth_blockNumber` method

### ISSUE THREAD

**Issue by ermvrs** [Digine-Labs/rosettanet#21]
## Description

We should get the RPC URL from the function inside utils. Request `starknet_blockNumber `. Then make a call to Starknet RPC. And return in the same format as Ethereum RPC.

## Requirements

- Unit tests have to be implemented. 
- Do not change the existing type structure

## Completion Time

The issue is assumed to be completed in 5 days. If you need more time, please also specify that.

**Comment by JimmyFate** [comment]
Hey :)
I think I could try complete this

**Comment by ermvrs** [comment]
Assigned

**Comment by ermvrs** [comment]
@all-contributors please add @JimmyFate for code, tests
