### ISSUE TITLE
Project README does not contain contribution guide

### ISSUE THREAD

**Issue by princeibs** [Digine-Labs/rosettanet#60]
<img width="608" alt="image" src="https://github.com/keep-starknet-strange/rosettanet/assets/64266194/7a97238d-92a6-40d9-99ac-536df8f1fb49">

This project appears to have the ```Newbies welcome``` badge on [OnlyDust](https://app.onlydust.com/p/rosettanet), but the README does not contain contribution guide newbies can use to get the project running on their machine. 

I would like to add the contribution guide and other details about the project to the README

**Comment by ermvrs** [comment]
I ll take care of that asap.

**Comment by princeibs** [comment]
The project seems interesting to me. Is there any other way I can contribute to it? @ermvrs

**Comment by ebukizy1** [comment]
will love to work on this ..

**Comment by ermvrs** [comment]
- [ ]
