### ISSUE TITLE
feat: Implement `eth_getBlockTransactionCountByHash` method

### ISSUE THREAD

**Issue by ermvrs** [Digine-Labs/rosettanet#65]
## Description

https://github.com/keep-starknet-strange/rosettanet/blob/main/rpc-call-examples/eth_getBlockTransactionCountByHash.hurl
https://github.com/keep-starknet-strange/rosettanet/blob/main/rpc-call-examples/starknet_getBlockTransactionCount.hurl

The same call exists. Just call starknet rpc and format the response like Ethereum.

## Requirements

- Unit tests have to be implemented. 
- Do not change the existing type structure

## Completion Time

The issue is assumed to be completed in 5 days. If you need more time, please also specify that.

**Comment by princeibs** [comment]
Hi @ermvrs, I can take on this one

**Comment by ermvrs** [comment]
Assigned

**Comment by ermvrs** [comment]
@all-contributors please add @princeibs for code,tests
